services:
  prometheus:
    image: prom/prometheus
    container_name: pavlovdi-netology-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - pavlovdi-my-netology-hw
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: pavlovdi-netology-grafana
    ports:
      - 80:3000
    networks:
      - pavlovdi-my-netology-hw
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=pavlovdi
      - GF_SECURITY_ADMIN_PASSWORD=netology
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
  pushgateway:
    image: prom/pushgateway
    container_name: pavlovdi-netology-pushgateway
    ports:
      - 9091:9091
    networks:
      - pavlovdi-my-netology-hw
    depends_on:
      - prometheus
    restart: unless-stopped
volumes:
  prom_data:
networks:
  pavlovdi-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1